# Generated by Django 6.1 on 2026-09-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leefanniv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='kind',
            field=models.CharField(choices=[('points', 'Classement à points'), ('bracket', 'Tableau à élimination')], default='points', max_length=10, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leefanniv.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leefanniv.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket', to='leefanniv.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leefanniv.team')),
            ],
            options={
                'ordering': ['round', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'round', 'slot'), name='uniq_bracket_slot')],
            },
        ),
    ]
