# Generated by Django 6.1 on 2026-09-26 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leefanniv', '0002_tournament_kind_bracketmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='draw_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='loss_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='win_points',
        ),
        migrations.AddField(
            model_name='game',
            name='emoji',
            field=models.CharField(default='🎲', max_length=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_points',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.5'), max_digits=5, verbose_name='égalité'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='loss_points',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='défaite'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='win_points',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=5, verbose_name='victoire'),
        ),
    ]
